config/routes.rb
Kindler::Application.routes.draw do
  resources :krindles
  
  get "facebook_users/list"
  
  

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
   root 'main#index'

   get 'main/kindles'

   get 'facebook_users/krindle/:krindle_id' => 'facebook_users#krindle'

   post 'facebook_users/krindle/:krindle_id' => 'facebook_users#krindle_save'

end

app/models/krindle.rb
class Krindle < ActiveRecord::Base
	has_many :krindlers
	has_many :users, through: :krindlers
end

app/models/krindle_pick.rb
class KrindlePick < ActiveRecord::Base
	belongs_to :user, :foreign_key => "user_id", :class_name => "User"
   	belongs_to :pick, :foreign_key => "pick_id", :class_name => "User" 
end

app/models/krindler.rb
class Krindler < ActiveRecord::Base
	belongs_to :user
	belongs_to :krindle
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :krindlers
  has_many :krindles, through: :krindlers

  has_many :krindle_picks, :foreign_key => "person_id", 
      :class_name => "KrindlePick"

  has_many :picks, :through => :friendships
  
  def self.from_omniauth(auth)
  	where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
    	user.provider = auth.provider
    	user.uid = auth.uid
    	user.name = auth.info.name
      user.picture = auth.info.image
    	user.oauth_token = auth.credentials.token
    	user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    	user.save!
  	end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
helper_method :current_user
  
end

app/controllers/facebook_users_controller.rb
class FacebookUsersController < ApplicationController
	skip_before_filter :verify_authenticity_token
  	def index
  	end

  	def list
   	if session[:user_id]
	      @user = User.find(session[:user_id])
	      @graph = Koala::Facebook::API.new(@user.oauth_token)
	      @friends = @graph.get_connections("me", "friends")
	      @people_list = Array.new
        @temp_list = Array.new
        @temp_list = @graph.get_object('me?fields=id,name,friends.fields(id,email,name,picture)')['friends']['data']
        @temp_list.each do |tp|
          @people_list << {'name'=>tp['name'], 'picture'=>tp['picture']['data']['url']}
	    	end
	 	end
	 	render :json=>@people_list
  	end

  def krindle
    @people_list=[]
    @people_list = Krindle.find(params['krindle_id']).users
    render :json=>@people_list
  end

  def krindle_save
    @krindle=Krindle.find(params['krindle_id'])
    added_users = params['krindle']
    @krindle.users = []
    added_users.each do |user|

      
    	@krindle.users<<User.find_or_create_by_id(:name=>user['name'], :uid=>user['id'], :picture=>user['picture'])
    end
    @krindle.save
    
    redirect_to :controller=>"krindles", :action=>""
  end

end

app/controllers/krindles_controller.rb
class KrindlesController < ApplicationController
  before_action :set_krindle, only: [:show, :edit, :update, :destroy]

  # GET /krindles
  # GET /krindles.json
  def index
    @krindles = Krindle.all
  end

  # GET /krindles/1
  # GET /krindles/1.json
  def show
     @user = User.find(session[:user_id])
     @graph = Koala::Facebook::API.new(@user.oauth_token)
  end

  # GET /krindles/new
  def new
    @krindle = Krindle.new
  end

  # GET /krindles/1/edit
  def edit
  end

  # POST /krindles
  # POST /krindles.json
  def create
    @krindle = Krindle.new(krindle_params)
    @user = User.find(session[:user_id])
    @krindle.users<<@user
    respond_to do |format|
      if @krindle.save
        format.html { redirect_to @krindle, notice: 'Krindle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @krindle }
      else
        format.html { render action: 'new' }
        format.json { render json: @krindle.errors, status: :unprocessable_entity }
      end
    end
  end



  # PATCH/PUT /krindles/1
  # PATCH/PUT /krindles/1.json
  def update
    respond_to do |format|
      if @krindle.update(krindle_params)
        format.html { redirect_to @krindle, notice: 'Krindle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @krindle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /krindles/1
  # DELETE /krindles/1.json
  def destroy
    @krindle.destroy
    respond_to do |format|
      format.html { redirect_to krindles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_krindle
      @krindle = Krindle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def krindle_params
      params.require(:krindle).permit(:name, :message)
    end

    def show_pick
      
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	if session[:user_id]
  		redirect_to action:'kindles'
  		return false
  	end

  end
  def kindles
  	@kindles = User.find(session[:user_id]).krindles
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facebook_users_helper.rb
module FacebookUsersHelper
end

app/helpers/krindles_helper.rb
module KrindlesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/krindles/_form.html.erb
<%= form_for(@krindle) do |f| %>
  <% if @krindle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@krindle.errors.count, "error") %> prohibited this krindle from being saved:</h2>

      <ul>
      <% @krindle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name, :size=>40 %>

  <%= f.label :message, "Message" %>
  <%= f.text_area :message, :size=>40 %>
  
  <%= f.label :max_amount, "Maximum amount to spend on a gift" %>
  <%= f.text_field :max_amount, :size=>40 %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/krindles/edit.html.erb
<h1>Editing krindle</h1>

<%= render 'form' %>

<%= link_to 'Show', @krindle %> |
<%= link_to 'Back', krindles_path %>

app/views/krindles/index.html.erb
<h1>Listing krindles</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @krindles.each do |krindle| %>
      <tr>
        <td><%= link_to 'Show', krindle %></td>
        <td><%= link_to 'Edit', edit_krindle_path(krindle) %></td>
        <td><%= link_to 'Destroy', krindle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Krindle', new_krindle_path %>

app/views/krindles/new.html.erb
<h1>New krindle</h1>

<%= render 'form' %>
<ul>

</ul>
<%= link_to 'Back', krindles_path %>

app/views/krindles/show.html.erb
<div ng-app="friendsApp">
	<h3>Add friends to your Kris Krindle</h3>
<input ng-model="query" placeholder="Find friends to add" class="search-box" />


<div ng-controller="MainCtrl" ng-init="init('<%= @krindle.id %>')" class="row">
	<div class="small-5 columns friends-list">
		<div ng-repeat="friend in friends | filter:query | orderBy:name">
			<div class="friend">
				<img src="{{friend.picture}}" class="left" />
				<strong class="left clearfix">{{friend.name}}</strong>
				<a href="" ng-click="addToKindle(friend)" class="button success small right">Add</a>
			</div>
		</div>
	</div>

	<div class="small-5 columns friends-list">
	
		<div ng-repeat="friend in friendsInKindle">
			<div class="friend">
				<img src="{{friend.picture}}"/>
				<strong class="left">{{friend.name}}</strong>
				<a href="" ng-click="removeFromKindle(friend)" class="button alert small right">Remove</a>
			</div>
		</div>
		
		<div ng-show="friendsInKindle.length" class="right save-btn">
			<a href="" ng-click="saveToKindle('<%= @krindle.id %>')" class="button small success">Save</a>
		</div>
	</div>
	
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en" itemscope itemtype="http://schema.org/WebApplication" prefix="og: http://ogp.me/ns#"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />
	
	<!-- Uncomment to make IE8 render like IE7 -->
	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
	
	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

	<meta name="description" content="Kris Kindle allows you to play Secret Santa with your family and friends. Share the joy of giving!" />

	<meta itemprop="description" content="Kris Kindle allows you to play Secret Santa with your family and friends. Share the joy of giving!">

	<meta property="og:title" content="Kris Kindle" />
	<meta property="og:type" content="website" />
	<!--<meta property="og:url" content="http://www.kris-kindle.com/" />-->
	<!-- <meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" /> -->
	<meta property="fb:app_id" content="289497607855017"/>
	<link rel="publisher" href="https://plus.google.com/111618093467441835278">

	<!--
  		<link rel="apple-touch-icon" href="http://1-ps.googleusercontent.com/x/s.html5rocks-hrd.appspot.com/www.html5rocks.com/static/images/identity/HTML5_Badge_64.png.pagespeed.ce.S0LMUsq9YG.png">
    	<link rel="apple-touch-icon-precomposed" href="http://1-ps.googleusercontent.com/x/s.html5rocks-hrd.appspot.com/www.html5rocks.com/static/images/identity/HTML5_Badge_64.png.pagespeed.ce.S0LMUsq9YG.png">
	-->
	
	<title><%= content_for?(:title) ? yield(:title) : "Kris Kindle" %></title>
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag    "application" %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="container">
  	<section>
  		<div class="row app">
			<%= yield %>
  		</div>
  	</section>
  </div>
  <%= javascript_include_tag "application", controller_name %>
</body>
</html>

app/views/main/index.html.erb
<div class="row">
	
	<h1>Kris Kindle</h1>
	<% unless session[:user_id].nil? %>
		<%= link_to 'Create a new Krindle', '/krindles/new', {:class=>"button medium round"}%>
	<% end -%>

</div>

<div class="row">
	
	<div class="columns small-4">			<% if current_user %>
    			Signed in as <strong><%= current_user.name %></strong>!
	    		<%= link_to "Sign out", signout_path, id: "sign_out" %>
  			<% else %>
    			<%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "button round right margin-right-10" %>
  			<% end %>
  		</div>
  		<div class="columns small-8">
	<h3>Is a Kris Kindle the same as a Secret Santa?</h3>
	
	<p>Exactly! What <a href="http://www.kris-kindle.com">kris-kindle.com</a> does, is make it easier to do a Secret Santa. If your family is anything like mine, getting everyone in the one place to pull names out of a hat can be really hard.</p>
	
	<p>Once you decide who you want to be in your kris kindle, <a href="http://www.kris-kindle.com">kris-kindle.com</a> will match your friends together, just like pulling names out of a hat.</p>

	<h3>But wait there's more!</h3>
	
	<p><a href="http://www.kris-kindle.com">kris-kindle.com</a> will even provide suggestions on what gifts to buy based on their facebook likes! So your family and friends will all get what they want this Christmas.</p>

	<h3>Sounds great! But how much is it?</h3>
	
	<p>Unfortunately, a great service like this doesn't come for free. Oh wait it does! That's right, just <%= link_to "login in with Facebook", "/auth/facebook", id: "sign_in" %> account and you are good to go! Think of it as an early Christmas present.</p>
	</div>
</div>

app/views/main/kindles.html.erb
<div class="row">
	<% unless @kindles.empty? -%>
		<% for kindle in @kindles %>
			<div class="panel krindle">
				<h3><%= kindle.name %></h3>
				<p>
					<%= link_to "Go to the Kris Kindle", url_for(kindle), class:"button small" %>
				</p>
			</div>
		<% end %>
	<% else -%>
		<h3>Hey, you are not in a Kris Kindle, why not set one up?</h3>
		<%= link_to 'Create a new Krindle', '/krindles/new', {:class=>"button medium round"} %>
	<% end -%>
</div>